// src/lib/attendancePages.ts
export const ATTENDANCE_PAGES: Array<{ key: string; label: string }> = [
  { key: "alannafreeoftv", label: "Alanna Free / OFTV" },
  { key: "alannapaid", label: "Alanna Paid" },
  { key: "alannawelcome", label: "Alanna Welcome" },
  { key: "alexalana", label: "Alexa Lana" },
  { key: "alexis", label: "Alexis" },
  { key: "allyfree", label: "Ally Free" },
  { key: "allypaid", label: "Ally Paid" },
  { key: "aprilb", label: "April B" },
  { key: "ashley", label: "Ashley" },
  { key: "asiadollpaidfree", label: "Asia Doll Paid / Free" },
  { key: "autumnfree", label: "Autumn Free" },
  { key: "autumnpaid", label: "Autumn Paid" },
  { key: "autumnwelcome", label: "Autumn Welcome" },
  { key: "brifreeoftv", label: "Bri Free / OFTV" },
  { key: "bripaid", label: "Bri Paid" },
  { key: "briwelcome", label: "Bri Welcome" },
  { key: "brittanyamain", label: "Brittanya Main" },
  { key: "brittanyapaidfree", label: "Brittanya Paid / Free" },
  { key: "bronwinfree", label: "Bronwin Free" },
  { key: "bronwinoftvmcarteroftv", label: "Bronwin OFTV & MCarter OFTV" },
  { key: "bronwinpaid", label: "Bronwin Paid" },
  { key: "bronwinwelcome", label: "Bronwin Welcome" },
  { key: "camipaid", label: "Cami Paid" },
  { key: "camifree", label: "Cami Free" },
  { key: "carterpaidfree", label: "Carter Paid / Free" },
  { key: "christipaidfree", label: "Christi Paid and Free" },
  { key: "claire", label: "Claire" },
  { key: "cocofree", label: "Coco Free" },
  { key: "cocopaid", label: "Coco Paid" },
  { key: "cynthiafree", label: "Cyndie, Cynthia & Colby" },
  { key: "dandfreeoftv", label: "Dan D Free / OFTV" },
  { key: "dandpaid", label: "Dan D Paid" },
  { key: "dandwelcome", label: "Dan D Welcome" },
  { key: "ella", label: "Ella" },
  { key: "emilyraypaidfree", label: "Emily Ray Paid / Free" },
  { key: "essiepaidfree", label: "Essie Paid / Free" },

  // ❌ REMOVED: fanslyteam1/2/3 (you said don’t count teams)

  { key: "francescapaid", label: "Francesca Paid" },
  { key: "gracefree", label: "Grace Free" },
  { key: "haileywfree", label: "Hailey W Free" },
  { key: "haileywpaid", label: "Hailey W Paid" },
  { key: "hazeyfree", label: "Hazey Free" },
  { key: "hazeypaid", label: "Hazey Paid" },
  { key: "hazeywelcome", label: "Hazey Welcome" },
  { key: "honeynoppv", label: "Honey NO PPV" },
  { key: "honeyvip", label: "Honey VIP" },
  { key: "isabellaxizziekay", label: "Isabella x Izzie Kay" },
  { key: "islafree", label: "Isla Free" },
  { key: "islaoftv", label: "Isla OFTV" },
  { key: "islapaid", label: "Isla Paid" },
  { key: "islawelcome", label: "Isla Welcome" },
  { key: "kayleexjasmyn", label: "Kaylee X Jasmyn" },
  { key: "kissingcousinsxvalerievip", label: "Kissing Cousins X Valerie VIP" },
  { key: "lexipaid", label: "Lexi Paid" },
  { key: "lilahfree", label: "Lilah Free" },
  { key: "lilahpaid", label: "Lilah Paid" },
  { key: "livv", label: "Livv" },
  { key: "lily", label: "Lily" },
  { key: "lucy", label: "Lucy" },
  { key: "madelynpaid", label: "Madelyn Paid" },
  { key: "madelynfree", label: "Madelyn Free" },
  { key: "madison", label: "Madison" },
  { key: "mathildefree", label: "Mathilde Free" },
  { key: "mathildepaid", label: "Mathilde Paid" },
  { key: "mathildewelcome", label: "Mathilde Welcome" },
  { key: "michellefree", label: "Michelle Free" },
  { key: "michellevip", label: "Michelle VIP" },
  { key: "mommycarter", label: "Mommy Carter" },
  { key: "natalialfree", label: "Natalia L Free" },
  { key: "natalialpaid", label: "Natalia L Paid" },
  { key: "natalialnicolefansly", label: "Natalia L, Nicole Fansly" },
  { key: "natalierfree", label: "Natalie R Free" },
  { key: "natalierpaid", label: "Natalie R Paid" },
  { key: "paris", label: "Paris" },
  { key: "popstfree", label: "Pops T Free" },
  { key: "popstpaid", label: "Pops T Paid" },
  { key: "rubirosefree", label: "Rubi Rose Free" },
  { key: "rubirosepaid", label: "Rubi Rose Paid" },
  { key: "salah", label: "Salah" },
  { key: "sarahc", label: "Sarah C" },
  { key: "skypaidfree", label: "Sky Paid / Free" },
  { key: "utahjazpaid", label: "UtahJaz Paid" },
  { key: "utahjazfree", label: "UtahJaz Free" },
];
