// src/lib/expectedPages.ts

export const RAW_PAGES: Record<string, string> = {
  alannafreeoftv: "Alanna Free / OFTV",
  alannapaid: "Alanna Paid",
  alannawelcome: "Alanna Welcome",
  alexalana: "Alexa Lana",
  alexis: "Alexis",
  allyfree: "Ally Free",
  allypaid: "Ally Paid",
  aprilb: "April B",
  ashley: "Ashley",
  asiadollpaidfree: "Asia Doll Paid / Free",
  autumnfree: "Autumn Free",
  autumnpaid: "Autumn Paid",
  autumnwelcome: "Autumn Welcome",
  brifreeoftv: "Bri Free / OFTV",
  bripaid: "Bri Paid",
  briwelcome: "Bri Welcome",
  brittanyamain: "Brittanya Main",
  brittanyapaidfree: "Brittanya Paid / Free",
  bronwinfree: "Bronwin Free",
  bronwinoftvmcarteroftv: "Bronwin OFTV & MCarter OFTV",
  bronwinpaid: "Bronwin Paid",
  bronwinwelcome: "Bronwin Welcome",
  camipaid: "Cami Paid",
  camifree: "Cami Free",
  carterpaidfree: "Carter Paid / Free",
  christipaidfree: "Christi Paid and Free",
  charlotteppaid: "Charlotte P Paid",
  charlottepfree: "Charlotte P Free",
  oaklypaidfree: "Oakly Paid / Free",
  claire: "Claire",
  cocofree: "Coco Free",
  cocopaid: "Coco Paid",
  cynthiafree: "Cyndie, Cynthia & Colby",
  dandfreeoftv: "Dan D Free / OFTV",
  dandpaid: "Dan D Paid",
  dandwelcome: "Dan D Welcome",
  emilyraypaidfree: "Emily Ray Paid / Free",
  emilyray: "Emily Ray",
  ella: "Ella",
  essiepaidfree: "Essie Paid / Free",
  fanslyteam1: "Fansly Team1",
  fanslyteam2: "Fansly Team2",
  fanslyteam3: "Fansly Team3",
  francescapaid: "Francesca Paid",
  gracefree: "Grace Free",
  haileywfree: "Hailey W Free",
  haileywpaid: "Hailey W Paid",
  hazeyfree: "Hazey Free",
  hazeypaid: "Hazey Paid",
  hazeywelcome: "Hazey Welcome",
  honeynoppv: "Honey NO PPV",
  honeyvip: "Honey VIP",
  isabellaxizziekay: "Isabella x Izzie Kay",
  kayleexjasmyn: "Kaylee X Jasmyn",
  kissingcousinsxvalerievip: "Kissing Cousins X Valerie VIP",
  lexipaid: "Lexi Paid",
  lilahfree: "Lilah Free",
  lilahpaid: "Lilah Paid",
  livv: "Livv",
  lily: "Lily",
  lucy: "Lucy",
  madelynpaid: "Madelyn Paid",
  madelynfree: "Madelyn Free",
  madison: "Madison",
  mathildefree: "Mathilde Free",
  mathildepaid: "Mathilde Paid",
  mathildewelcome: "Mathilde Welcome",
  michellefree: "Michelle Free",
  michellevip: "Michelle VIP",
  mommycarter: "Mommy Carter",
  natalialfree: "Natalia L Free",
  natalialpaid: "Natalia L Paid",
  natalialnicolefansly: "Natalia L, Nicole Fansly",
  natalierfree: "Natalie R Free",
  natalierpaid: "Natalie R Paid",
  paris: "Paris",
  popstfree: "Pops T Free",
  popstpaid: "Pops T Paid",
  rubirosefree: "Rubi Rose Free",
  rubirosepaid: "Rubi Rose Paid",
  salah: "Salah",
  sarahc: "Sarah C",
  skypaidfree: "Sky Paid / Free",
  utahjazpaid: "UtahJaz Paid",
  utahjazfree: "UtahJaz Free",
  utahjazwelcome: "UtahJaz Welcome",
  
  // ...continue your list (copy all from your bot)
};

export function normalizeTag(tag: string) {
  return tag
    .toLowerCase()
    .replace(/[\s_\/&]/g, "")
    .replace(/x/g, "");
}

// This is your EXPECTED_PAGES equivalent (normalized keys)
export const EXPECTED_PAGES: Record<string, string> = Object.fromEntries(
  Object.entries(RAW_PAGES).map(([k, v]) => [normalizeTag(k), v])
);
